const actionTypes = {
  SET_ACTION: 'SET_ACTION',
  SET_OPTIONS: 'SET_OPTIONS',
  SET_TOOL: 'SET_TOOL',
  SET_OUTPUT_FOLDER: 'SET_OUTPUT_FOLDER',
  SET_URL: 'SET_URL',
  SET_FILE_ORIGIN: 'SET_FILE_ORIGIN',
  UPDATE_LANGUAGE: 'UPDATE_LANGUAGE',
  UPDATE_PDF_TOOL: 'UPDATE_PDF_TOOL',
  UPDATE_JPEG_TOOL: 'UPDATE_JPEG_TOOL',
  UPLOAD_FILE: 'UPLOAD_FILE',
};

export default actionTypes;
