const actionTypes = {
  SET_ACTION: 'SET_ACTION',
  SET_OPTIONS: 'SET_OPTIONS',
  SET_TOOL: 'SET_TOOL',
  SET_OUTPUT_FOLDER: 'SET_OUTPUT_FOLDER',
  SET_URL: 'SET_URL',
  SET_FILE_ORIGIN: 'SET_FILE_ORIGIN',
  UPDATE_PDF_TOOL: 'UPDATE_PDF_TOOL',
  UPDATE_JPEG_TOOL: 'UPDATE_JPEG_TOOL',
  SET_FILE_PATH: 'SET_FILE_PATH',
  SET_FILE_NAME: 'SET_FILE_NAME',
};

export default actionTypes;
