const actionTypes = {
  SET_ACTIONS: 'SET_ACTIONS',
  SET_ACTION: 'SET_ACTION',
  SET_ACTION_TYPE: 'SET_ACTION_TYPE',
  SET_OPTIONS: 'SET_OPTIONS',
  SET_TOOL: 'SET_TOOL',
  SET_OUTPUT_FOLDER: 'SET_OUTPUT_FOLDER',
  SET_URL: 'SET_URL',
  SET_FILE_ORIGIN: 'SET_FILE_ORIGIN',
  UPDATE_PDF_TOOL: 'UPDATE_PDF_TOOL',
  UPDATE_JPEG_TOOL: 'UPDATE_JPEG_TOOL',
  SET_DIR_PATH: 'SET_DIR_PATH',
  SWITCH_ACTION: 'SWITCH_ACTION',
  SET_DEFAULT_PDF_TOOl: 'SET_DEFAULT_PDF_TOOl',
  SET_FILE_INFO: 'SET_FILE_INFO',
  SET_PAR_DATA: 'SET_PAR_DATA',
  SET_MIME_TYPE: 'SET_MIME_TYPE',
  SET_CONFIG: 'SET_CONFIG',
  SET_LOAD: 'SET_LOAD',
};

export default actionTypes;
